### ISSUE TITLE
Set up CI/CD 

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/IFC_Toolkit#2]
#### Description:
Once #1 is resolved, it would be good to set up the basic CI/CD checks - not necessarily as required, but at least as indicators of how close to the ideal the code is. What do you think @FraserGreenroyd?

**Comment by FraserGreenroyd** [comment]
BHoMBot will already be listening to any PRs raised. Further checks only needed if the toolkit goes into an installer

**Comment by pawelbaran** [comment]
That was quick 😃 thanks @FraserGreenroyd!
